import { Component, createEffect, createSignal, onCleanup } from 'solid-js'

export type AppLanguage = 'zh-CN' | 'en'

export const LANGUAGE_STORAGE_KEY = 'agnai.language'

const ZH_CN: Record<string, string> = {
  Settings: '设置',
  Close: '关闭',
  Cancel: '取消',
  Confirm: '确认',
  Information: '信息',
  AI: 'AI',
  UI: '界面',
  Voice: '语音',
  'Guest Data': '访客数据',
  Subscription: '订阅',
  Language: '语言',
  'Update Settings': '更新设置',
  'Delete Guest State': '删除访客状态',
  'This cannot be undone!': '此操作不可撤销！',
  Login: '登录',
  Register: '注册',
  Welcome: '欢迎',
  Authorizing: '正在授权',
  'You are already logged in.': '你已经登录。',
  'to your account or': '到你的账户，或',
  'or continue as a guest.': '或以访客身份继续。',
  'Failed to log in.': '登录失败。',
  "We couldn't reach our servers.": '无法连接到服务器。',
  'Something went wrong.': '出现了一些问题。',
  'Passwords do not match': '两次输入的密码不一致',
  'Display Name': '显示名称',
  'Display name': '显示名称',
  Username: '用户名',
  Password: '密码',
  'Confirm Password': '确认密码',
  'Registering...': '正在注册...',
  'Logging in...': '正在登录...',
  'Invalid callback URL': '无效的回调 URL',
  'Why register?': '为什么注册？',
  'Terms': '条款',
  'Privacy Policy': '隐私政策',
  'Term of Service': '服务条款',
  'Terms of Service': '服务条款',
  'Main': '主导航',
  'Agnaistic main page': 'Agnaistic 主页',
  'Version': '版本',
  'Character hub': '角色中心',
  CharHub: '角色中心',
  CHUB: '角色中心',
  Characters: '角色',
  Chats: '聊天',
  Presets: '预设',
  Library: '资料库',
  Sounds: '音效',
  Persona: '人设',
  'Sagas Preview': 'Sagas 预览',
  'Manage': '管理后台',
  'Server Configuration': '服务器配置',
  'User Management': '用户管理',
  'Subscriptions': '订阅与模型',
  'Announcements': '公告管理',
  'Login to the application': '登录应用',
  'Add a new preset': '新增预设',
  'Add a new character': '新增角色',
  'Create a new chat': '创建新聊天',
  'Show notification list': '显示通知列表',
  'Status: No new notifications': '状态：没有新通知',
  'Email Support': '邮件支持',
  'Open FAQ page': '打开常见问题页',
  'Open settings page': '打开设置页',
  'Image Generation': '图像生成',
  'Toggle between light and dark mode': '切换明暗模式',
  'Edit user profile': '编辑用户资料',
  'Open impersonation menu': '打开扮演菜单',
  'Subscribe for higher quality chats and no ads': '订阅以获得更高质量的聊天并移除广告',
  'Login issues? Try': '登录有问题？请尝试',
  'Logging out': '退出登录',
  'then log back in.': '然后重新登录。',
  'Page loading issues? Try': '页面加载有问题？请尝试',
  'clicking here': '点击这里',
  'Agnaistic failed to load': 'Agnaistic 加载失败',
  'Try Again': '重试',
  'Account Banned': '账户已被封禁',
  'This account has been banned for the following reason:': '此账户因以下原因被封禁：',
  'If you believe this is an error, please contact support.': '如果你认为这是误封，请联系支持。',
  'Recent Conversations': '最近对话',
  'Start Conversation': '开始对话',
  'Start conversation': '开始对话',
  'Create a Character': '创建角色',
  'Create a character': '创建角色',
  'Configure your AI Services': '配置你的 AI 服务',
  'Getting Started': '快速开始',
  Guides: '指南',
  Links: '链接',
  'Official Guides': '官方指南',
  'Memory Book': '记忆书',
  'Notable Features': '主要功能',
  Import: '导入',
  Create: '创建',
  Edit: '编辑',
  Select: '选择',
  Delete: '删除',
  Archive: '归档',
  Unarchive: '取消归档',
  Download: '下载',
  Done: '完成',
  'Last Modified': '最后修改',
  'Last Conversed': '最后对话',
  Created: '创建时间',
  Name: '名称',
  'Search by name...': '按名称搜索...',
  'List View': '列表视图',
  'Cards View': '卡片视图',
  'Folder View': '文件夹视图',
  'Selected: None': '已选择：无',
  Selected: '已选择',
  Favorites: '收藏',
  'Failed to load characters. Refresh to try again.': '角色加载失败，请刷新后重试。',
  'No characters found': '没有找到角色',
  'Create a character': '创建角色',
  'to get started!': '开始使用！',
  Editing: '正在编辑',
  'Archive characters?': '要归档角色吗？',
  'Unarchive characters?': '要取消归档角色吗？',
  'Are you sure you wish to delete characters?': '确定要删除这些角色吗？',
  'Chat Activity': '聊天活跃度',
  'Bot Activity': '角色活跃度',
  'Chat Created': '聊天创建时间',
  'Bot Name': '角色名称',
  'Bot Created': '角色创建时间',
  'Chat Counts': '聊天数量',
  New: '新建',
  'Search...': '搜索...',
  'All Characters': '全部角色',
  'No conversations': '没有对话',
  'Are you sure you wish to delete the conversation?': '确定要删除这段对话吗？',
  'You have no conversations yet.': '你还没有任何对话。',
  'You have no conversations with': '你还没有与以下角色对话：',
  Unknown: '未知',
  Models: '模型',
  'Horde Guide': 'Horde 指南',
  'Horde guide': 'Horde 指南',
  'OpenAI Guide': 'OpenAI 指南',
  'OpenAI guide': 'OpenAI 指南',
  Important: '重要',
  'Horde Settings': 'Horde 设置',
  Update: '更新',
  Copy: '复制',
  'Create character': '创建角色',
  'Edit character': '编辑角色',
  'Copy character': '复制角色',
  'a Character': '角色',
  'AI Character Generation Guide': 'AI 角色生成指南',
  Preset: '预设',
  Export: '导出',
  'Are you sure you wish to clear the editor?': '确定要清空编辑器吗？',
  'Character Name': '角色名称',
  "Description / Creator's notes": '描述 / 作者备注',
  'A description, label, or notes for your character. This is will not influence your character in any way.':
    '角色的描述、标签或备注。它不会以任何方式影响角色表现。',
  Tags: '标签',
  'Used to help you organize and filter your characters.': '用于帮助你整理和筛选角色。',
  Scenario: '场景',
  'The current circumstances and context of the conversation and the characters.':
    '当前对话和角色所处的环境与上下文。',
  'Personality': '性格',
  'If you do not know what this mean, you can leave this as-is.':
    '如果你不知道这是什么意思，可以保持原样。',
  'WARNING: "Plain Text" and "Non-Plain Text" schemas are not compatible. Changing between them will cause data loss.':
    '警告：“纯文本”和“非纯文本”结构不兼容，切换会导致数据丢失。',
  "Format to use for the character's format": '角色人设使用的格式。',
  Greeting: '开场白',
  'The first message from your character. It is recommended to provide a lengthy first message to encourage the character to give longer responses.':
    '角色发送的第一条消息。建议提供较长的开场白，以鼓励角色给出更长回复。',
  'Sample Conversation': '示例对话',
  'Example chat between you and the character. This section is very important for teaching your character should speak.':
    '你和角色之间的示例聊天。这个部分对塑造角色说话方式非常重要。',
  'Disable Character\'s Voice': '禁用角色语音',
  'Toggle on to disable this character from automatically speaking':
    '开启后，此角色不会自动朗读。',
  'The language this character speaks and understands.': '该角色使用和理解的语言。',
  'Image Settings have moved: Click the': '图像设置已移动：请点击主菜单中的',
  'in the main menu': '。',
  'Update Preset': '更新预设',
  'This preset used for character generation': '此预设用于角色生成。',
  'Confirm Deletion': '确认删除',
  'This will delete all of the chats associated with this character!':
    '这会删除与该角色关联的所有聊天！',
  'Are you sure you wish to delete this character?': '确定要删除这个角色吗？',
  'Successfully downloaded from Character Hub': '已成功从 Character Hub 下载',
  'Character load failed (ID missing?) - Try again or contact support':
    '角色加载失败（缺少 ID？）请重试或联系支持。',
  None: '无',
  'Unnamed Preset': '未命名预设',
  Participants: '参与者',
  'Edit Chat': '编辑聊天',
  Memory: '记忆',
  'Chat Graph': '聊天图谱',
  'Site Settings': '站点设置',
  'Download Chat': '下载聊天',
  'Restart Chat': '重启聊天',
  'Delete Chat': '删除聊天',
  'You have been removed from the conversation': '你已被移出该对话',
  'Send a message... (OOC)': '发送消息...（旁白/OOC）',
  'Send a message to': '发送消息给',
  'Send a message...': '发送消息...',
  'Confirm or cancel swiping before sending': '发送前请先确认或取消切换回复',
  'Could not play voice: No character message found': '无法播放语音：未找到角色消息',
  'Invalid file type: Must be an image': '文件类型无效：必须是图片',
  'Attachment exceeds size limit (1MB)': '附件超过大小限制（1MB）',
  Leaf: '叶节点',
  Cutoff: '截断',
  'Response hint...': '回复提示...',
  'Open impersonation menu': '打开扮演菜单',
  'Respond as Me': '以我身份回复',
  'Auto-reply': '自动回复',
  'Stop Bot Reply': '停止角色回复',
  'Generate Image': '生成图片',
  'Respond Again': '重新回复',
  'Generate More': '继续生成',
  'Play Voice': '播放语音',
  'Trigger Event': '触发事件',
  'Attach Image': '附加图片',
  'Export Chat': '导出聊天',
  'Confirm Delete': '确认删除',
  'Are you sure you wish to delete this chat?': '确定要删除这个聊天吗？',
  'Edit Character': '编辑角色',
  'Temporary character updated': '临时角色已更新',
  'Memory Guide': '记忆指南',
  'UI Settings': '界面设置',
  'Chat Settings': '聊天设置',
  'Create Chat': '创建聊天',
  'You have no scenarios': '你还没有场景',
  'System Built-in Preset (Horde)': '系统内置预设（Horde）',
  'System Built-in Preset': '系统内置预设',
  'Your Default Preset': '你的默认预设',
  'Optionally modify some of the conversation context. You can override other aspects of the character\'s persona from the conversation after it is created.':
    '你可以选择修改部分对话上下文。对话创建后，也可以在对话中覆盖角色人设的其他部分。',
  'The information provided here is only applied to the newly created conversation.':
    '这里提供的信息只会应用到新创建的对话。',
  Character: '角色',
  "The conversation's main character": '这个对话的主角色',
  'Chat Mode': '聊天模式',
  'COMPANION: Everything is permanent. You will not be able to: Edit Chat, Retry Message, Delete Messages, etc.':
    '陪伴模式：所有内容都会固定保存。你将无法编辑聊天、重试消息、删除消息等。',
  Conversation: '对话',
  Companion: '陪伴',
  'Conversation Name': '对话名称',
  'A name for the conversation. This is purely for labelling.': '对话的名称，仅用于标记。',
  '(Optional)': '（可选）',
  Untitled: '未命名',
  'Override Character Definitions': '覆盖角色定义',
  'Overrides will only apply to the newly created conversation.': '覆盖内容只会应用到新创建的对话。',
  'The scenario to use for this conversation': '这个对话要使用的场景',
  'Sample Chat': '示例聊天',
  'Plain text': '纯文本',
  'Reset Character': '重置角色',
  Save: '保存',
  'Image Source': '图像来源',
  'Which settings to use when generating images for this chat': '为这个聊天生成图片时使用哪组设置',
  'Main Character': '主角色',
  'Last Character to Speak': '最后发言的角色',
  'Chat Settings': '聊天设置',
  'App Settings': '应用设置',
  'Background Image': '背景图片',
  Auto: '自动',
  Cover: '覆盖',
  Contain: '包含',
  Remove: '移除',
  'The image will be stored on your current device and not available on other devices':
    '图片会保存在当前设备上，其他设备无法使用。',
  'Warning! Switching to COMPANION mode is irreversible! You will no longer be able to: retry messages, delete chats, edit chat settings.':
    '警告！切换到陪伴模式后不可逆！你将无法重试消息、删除聊天或编辑聊天设置。',
  'Chat name': '聊天名称',
  'Generate one name for this conversation. Reply only with the one chat name only and no other formatting or commentary.':
    '为这个对话生成一个名称。只回复一个聊天名称，不要包含其他格式或说明。',
  'Conversation Name Generator': '对话名称生成器',
  "Overrides apply to this chat only. If you want to edit the original character, open the 'Character' link in the Chat Menu instead.":
    '覆盖内容只应用于这个聊天。如果你想编辑原始角色，请从聊天菜单打开“角色”链接。',
  'The current state of the scenario': '场景当前状态',
  'What flags have been set in the chat by the scenario so far': '目前场景在聊天中设置了哪些标记',
  'Description': '描述',
  'A description, label, or notes for your character: Used for AI field generation. Does not change your character\'s behavior.':
    '角色的描述、标签或备注：用于 AI 字段生成，不会改变角色行为。',
  'Character System Prompt': '角色系统提示词',
  'Character Post-History Instructions': '角色历史后指令',
  'Default Message Visibility': '默认消息可见性',
  Visible: '可见',
  Invisible: '不可见',
  'Not Set': '未设置',
  'Defaults for All Messages': '所有消息的默认设置',
  'Agnaistic loading...': 'Agnaistic 加载中...',
  'Notes from the creator of': '来自创建者的备注：',
  'Generate Message': '生成消息',
  'Are you sure?': '确定吗？',
  'This will fork your conversation from the greeting message.': '这会从开场白消息开始分叉当前对话。',
  'Temp Character': '临时角色',
  'Temporary Character': '临时角色',
  User: '用户',
  Back: '返回',
  'Temporary Characters': '临时角色',
  'Deleted Temporary Characters': '已删除的临时角色',
  'Are you sure you wish to remove': '确定要移除',
  'You don\'t have any other characters to invite': '你没有其他可邀请的角色',
  'Select a character to add to the chat': '选择一个角色加入聊天',
  'You don\'t have any characters available to add': '没有可添加的角色',
  'No user ID provided': '未提供用户 ID',
  'Invite User': '邀请用户',
  'The ID of the user to invite. The user should provide this to you': '要邀请的用户 ID。对方需要把这个 ID 提供给你。',
  'Send Invite': '发送邀请',
  'Chat Owner': '聊天所有者',
  'Supported Providers': '支持的服务商',
  'Local / Self-Host': '本地 / 自托管',
  Custom: '自定义',
  'Provider: Choose a Provider': '服务商：请选择服务商',
  'Provider:': '服务商：',
  'URL is not valid. Check it and try again': 'URL 无效，请检查后重试',
  'Update Provider': '更新服务商',
  'Create Provider': '创建服务商',
  'Provide connection details to use an external service': '填写连接信息以使用外部服务',
  Label: '标签',
  'Custom label for this provider': '这个服务商的自定义标签',
  URL: 'URL',
  'API Key': 'API Key',
  'Key is set': '密钥已设置',
  'E.g. sk-...': '例如 sk-...',
  'Disable Auto-URL': '禁用自动 URL',
  'Request Format': '请求格式',
  'Test Connection': '测试连接',
  'Select Provider': '选择服务商',
  Providers: '服务商',
  Service: '服务',
  'Providers are used to connect to your preferred AI models.':
    '服务商用于连接你想使用的 AI 模型。',
  'Click **`+ New`** to create a new provider and fill in the information.':
    '点击 **`+ 新建`** 创建服务商并填写连接信息。',
  '**Format**\nIf you prompted to select a **Format** and you are not sure one to use, select `Chat`.':
    '**格式**\n如果系统要求选择 **格式**，而你不确定该选哪个，请选择 `Chat`。',
  '**Important**: Make sure the correct provider is chosen in the dropdown below in your props.state.':
    '**重要**：请确认下方下拉框里选中了正确的服务商。',
  'Legacy:': '旧配置：',
  'Edit Connection Details': '编辑连接详情',
  Accept: '接受',
  'AI Service': 'AI 服务',
  'Warning! Your preset does not currently have a service set.':
    '警告！你的预设当前尚未设置服务。',
  'Third-Party Format': '第三方格式',
  'Controls how requests are sent': '控制请求的发送方式',
  'API URL for **third-party** or **self-hosted** services':
    '**第三方** 或 **自托管** 服务的 API URL',
  'E.g. https://some-tunnel-url.loca.lt': '例如 https://some-tunnel-url.loca.lt',
  'Remove Key': '移除密钥',
  'Never enter your official OpenAI, Claude, Mistral keys here.':
    '不要在这里输入你的官方 OpenAI、Claude、Mistral 密钥。',
}

const getStoredLanguage = (): AppLanguage => {
  if (typeof localStorage === 'undefined') return 'zh-CN'
  return localStorage.getItem(LANGUAGE_STORAGE_KEY) === 'en' ? 'en' : 'zh-CN'
}

const [language, setLanguageSignal] = createSignal<AppLanguage>(getStoredLanguage())

export const appLanguage = language

export function getAppLanguage(): AppLanguage {
  return language()
}

export function setAppLanguage(next: AppLanguage) {
  localStorage.setItem(LANGUAGE_STORAGE_KEY, next)
  setLanguageSignal(next)
  document.documentElement.lang = next
  window.dispatchEvent(new CustomEvent('agnai-language-change', { detail: next }))
}

export function t(key: string) {
  if (language() === 'en') return key
  return ZH_CN[key] || key
}

const AdminChineseLocalizer: Component = () => {
  createEffect(() => {
    document.documentElement.lang = language()
  })

  const onStorage = (event: StorageEvent) => {
    if (event.key !== LANGUAGE_STORAGE_KEY) return
    setLanguageSignal(getStoredLanguage())
  }

  window.addEventListener('storage', onStorage)
  onCleanup(() => window.removeEventListener('storage', onStorage))

  return null
}

export default AdminChineseLocalizer
